workflows:
  react-native-budgetwise-debug:
    name: BudgetWise Debug APK Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.budgetwise"
      node: 18.19.0
      xcode: 15.2
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true
        - pattern: feature/*
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Install CocoaPods dependencies (for iOS dependencies)
        script: |
          cd ios && pod install
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
      - name: List generated APK files
        script: |
          find android/app/build/outputs/apk/debug -name "*.apk" -type f
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/logs/*.log
    publishing:
      email:
        recipients:
          - your-email@domain.com # Replace with your email
        notify:
          success: true
          failure: true

  # Manual trigger workflow for on-demand builds
  react-native-budgetwise-manual:
    name: BudgetWise Manual Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.budgetwise"
      node: 18.19.0
      xcode: 15.2
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    when:
      condition: $CM_BUILD_TRIGGER == 'manual'
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Run linting
        script: |
          npm run lint
      - name: Run tests (if any)
        script: |
          npm test -- --watchAll=false || echo "No tests found, skipping..."
      - name: Type checking
        script: |
          npx tsc --noEmit
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Clean Android build
        script: |
          cd android
          ./gradlew clean
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
      - name: Display APK information
        script: |
          APK_PATH=$(find android/app/build/outputs/apk/debug -name "*.apk" -type f | head -1)
          if [ -f "$APK_PATH" ]; then
            echo "✅ APK built successfully!"
            echo "📁 APK Location: $APK_PATH"
            echo "📦 APK Size: $(du -h "$APK_PATH" | cut -f1)"
            echo "📱 Package Name: com.budgetwise"
            echo "🔧 Build Type: Debug"
            echo ""
            echo "📋 To install on your device:"
            echo "1. Download the APK from Codemagic artifacts"
            echo "2. Enable 'Install from unknown sources' on your Android device"
            echo "3. Transfer the APK to your device and install"
          else
            echo "❌ APK not found!"
            exit 1
          fi
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/logs/*.log
    publishing:
      email:
        recipients:
          - hetp7986@gmail.com # Replace with your email
        notify:
          success: true
          failure: true
