workflows:
  react-native-budgetwise-debug:
    name: BudgetWise Debug APK Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.budgetwise"
      node: 18.19.0
      xcode: 15.2
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true
        - pattern: feature/*
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Install CocoaPods dependencies (for iOS dependencies)
        script: |
          cd ios && pod install
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
      - name: List generated APK files
        script: |
          find android/app/build/outputs/apk/debug -name "*.apk" -type f
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/logs/*.log
    publishing:
      email:
        recipients:
          - hetp7986@gmail.com # Replace with your email
        notify:
          success: true
          failure: true
