workflows:
  android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      node: 16.13.1
      java: 11
    scripts:
      - npm install
      - chmod +x android/gradlew
      - cd android
      - ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
