workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.npm
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Clean build directory
        script: |
          cd android
          ./gradlew clean
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Make Gradle wrapper executable
        script: |
          cd android
          chmod +x ./gradlew
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - hetp7986@gmail.com
