workflows:
  android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 16.13.1
    scripts:
      - npm install
      - cd android
      - ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
